apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-ingress

resources:
  - ./gateway.yaml
  - ./gateway-class.yaml
  - ./gateway-certificate.yaml
  - ./coraza-plugin.yaml
  