apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nginx-echo-headers
spec:
  parentRefs:
  - name: main
    namespace: openshift-ingress
  hostnames: ["nginx-echo-headers.gwapi.${CLUSTER_BASE_DOMAIN}"]
  rules:
  - backendRefs:
    - name: nginx-echo-headers
      port: 8080