applications:

  patch-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: patch-operator
    source:
      path: components/patch-operator 

  cert-manager-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: cert-manager
    source:
      path: components/cert-manager-operator    

  cert-manager-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: cert-manager
    source:
      path: components/cert-manager-configuration
    extraFields: |
      ignoreDifferences:
        - group: 'cert-manager.io'
          jsonPointers:
            - /spec/acme/solvers
          kind: ClusterIssuer   

  openshift-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '7'
    destination:
      namespace: openshift-config
    source:
      path: components/openshift-config 

  gateway-api:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '8'
    destination:
      namespace: openshift-ingress
    source:
      path: components/gateway-api

  kiali-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-kiali-operator
    source:
      path: components/kiali-operator

  kiali:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-ingress
    source:
      path: components/kiali                           
                          
  openshift-servicemesh:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-servicemesh-operator
    source:
      path: components/openshift-servicemesh                          