applications:

  patch-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: patch-operator
    source:
      path: components/patch-operator 

  cert-manager-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: cert-manager
    source:
      path: components/cert-manager-operator    

  cert-manager-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: cert-manager
    source:
      path: components/cert-manager-configuration
    extraFields: |
      ignoreDifferences:
        - group: 'cert-manager.io'
          jsonPointers:
            - /spec/acme/solvers
          kind: ClusterIssuer   

  openshift-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: openshift-config
    source:
      path: components/openshift-config                 
                          
  openshift-servicemesh:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-servicemesh-operator
    source:
      path: components/openshift-servicemesh                          