apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true
spec:
  featureSet: CustomNoUpgrade
  customNoUpgrade:
    enabled:
      - GatewayAPI